--!strict
--[[
    Endware UI v0.1.1 — generated single-file distribution.

    DO NOT EDIT THIS FILE DIRECTLY.
    Edit src/Endware and rebuild the bundle instead.

    This file performs no HTTP requests. It only returns the Endware API table.
]]

local __modules: {[string]: (any) -> any} = {}
local __cache: {[string]: any} = {}
local __loading: {[string]: boolean} = {}

__modules["Utility/Create"] = function(__require)

local function Create(className: string, properties: {[string]: any}?, children: {Instance}?): any
	local instance = Instance.new(className)
	local dynamicInstance = instance :: any
	local parent: Instance? = nil
	if properties then
		for property, value in pairs(properties) do
			if property == "Parent" then
				parent = value
			else
				dynamicInstance[property] = value
			end
		end
	end
	if children then
		for _, child in ipairs(children) do
			child.Parent = instance
		end
	end
	if parent then
		instance.Parent = parent
	end
	return instance
end

return Create

end

__modules["Utility/Tween"] = function(__require)

local TweenService = game:GetService("TweenService")

local Tween = {}
local active: {[Instance]: Tween} = setmetatable({}, { __mode = "k" }) :: any

function Tween.Cancel(instance: Instance)
	local current = active[instance]
	if current then
		current:Cancel()
		active[instance] = nil
	end
end

function Tween.Play(
	cleanup: any,
	instance: Instance,
	duration: number,
	goal: {[string]: any},
	reducedMotion: boolean?,
	style: Enum.EasingStyle?,
	direction: Enum.EasingDirection?
): Tween?
	Tween.Cancel(instance)
	local dynamicInstance = instance :: any
	if reducedMotion or duration <= 0 then
		for property, value in pairs(goal) do
			dynamicInstance[property] = value
		end
		return nil
	end
	local tween = TweenService:Create(
		instance,
		TweenInfo.new(duration, style or Enum.EasingStyle.Quint, direction or Enum.EasingDirection.Out),
		goal
	)
	active[instance] = tween
	cleanup:Give(tween)
	cleanup:Give(tween.Completed:Connect(function()
		if active[instance] == tween then
			active[instance] = nil
		end
	end))
	tween:Play()
	return tween
end

return Tween

end

__modules["Utility/Input"] = function(__require)

local UserInputService = game:GetService("UserInputService")

local Input = {}

function Input.IsPrimary(input: InputObject): boolean
	return input.UserInputType == Enum.UserInputType.MouseButton1
		or input.UserInputType == Enum.UserInputType.Touch
end

function Input.IsPointerMove(input: InputObject): boolean
	return input.UserInputType == Enum.UserInputType.MouseMovement
		or input.UserInputType == Enum.UserInputType.Touch
end

function Input.HasFocusedTextBox(): boolean
	return UserInputService:GetFocusedTextBox() ~= nil
end

function Input.IsTouchDevice(): boolean
	return UserInputService.TouchEnabled
end

return Input

end

__modules["Utility/Math"] = function(__require)

local Math = {}

function Math.RoundToStep(value: number, step: number): number
	if step <= 0 then
		return value
	end
	return math.round(value / step) * step
end

function Math.ClampPoint(point: Vector2, size: Vector2, bounds: Vector2, margin: number?): Vector2
	local safeMargin = margin or 8
	local maxX = math.max(safeMargin, bounds.X - size.X - safeMargin)
	local maxY = math.max(safeMargin, bounds.Y - size.Y - safeMargin)
	return Vector2.new(
		math.clamp(point.X, safeMargin, maxX),
		math.clamp(point.Y, safeMargin, maxY)
	)
end

return Math

end

__modules["Utility/Validation"] = function(__require)

local Validation = {}

function Validation.RequiredString(value: any, fieldName: string): string
	assert(type(value) == "string" and #value > 0, string.format("[Endware] %s must be a non-empty string.", fieldName))
	return value
end

function Validation.NumberRange(minimum: number, maximum: number)
	assert(maximum > minimum, "[Endware] Slider Max must be greater than Min.")
end

function Validation.Array(value: any, fieldName: string): {any}
	assert(type(value) == "table", string.format("[Endware] %s must be an array.", fieldName))
	return value
end

return Validation

end

__modules["Core/Cleanup"] = function(__require)

local Cleanup = {}
Cleanup.__index = Cleanup

type Cleanup = typeof(setmetatable({} :: {
	_tasks: {any},
	_destroyed: boolean,
}, Cleanup))

local function dispose(taskValue: any)
	local valueType = typeof(taskValue)
	if valueType == "RBXScriptConnection" then
		if taskValue.Connected then
			taskValue:Disconnect()
		end
	elseif valueType == "Instance" then
		taskValue:Destroy()
	elseif valueType == "function" then
		taskValue()
	elseif valueType == "Tween" then
		taskValue:Cancel()
	elseif type(taskValue) == "table" then
		if type(taskValue.Destroy) == "function" then
			taskValue:Destroy()
		elseif type(taskValue.Cleanup) == "function" then
			taskValue:Cleanup()
		elseif type(taskValue.Cancel) == "function" then
			taskValue:Cancel()
		end
	end
end

function Cleanup.new(): Cleanup
	return setmetatable({
		_tasks = {},
		_destroyed = false,
	}, Cleanup)
end

function Cleanup:Give<T>(taskValue: T): T
	if self._destroyed then
		dispose(taskValue)
		return taskValue
	end
	table.insert(self._tasks, taskValue)
	return taskValue
end

function Cleanup:Cleanup()
	if self._destroyed then
		return
	end
	for index = #self._tasks, 1, -1 do
		local taskValue = self._tasks[index]
		self._tasks[index] = nil
		local ok, message = pcall(dispose, taskValue)
		if not ok then
			warn("[Endware] Cleanup task failed: " .. tostring(message))
		end
	end
end

function Cleanup:Destroy()
	if self._destroyed then
		return
	end
	self:Cleanup()
	self._destroyed = true
end

return Cleanup

end

__modules["Theme"] = function(__require)

type Theme = {
	Background: Color3,
	Panel: Color3,
	Surface: Color3,
	SurfaceRaised: Color3,
	SurfaceHover: Color3,
	Text: Color3,
	TextMuted: Color3,
	Accent: Color3,
	AccentPressed: Color3,
	Positive: Color3,
	Warning: Color3,
	Danger: Color3,
	Outline: Color3,
	Shadow: Color3,
	Overlay: Color3,
	FontDisplay: Enum.Font,
	FontBody: Enum.Font,
	FontBold: Enum.Font,
	TextTitle: number,
	TextHeading: number,
	TextBody: number,
	TextSmall: number,
	CornerWindow: number,
	CornerCard: number,
	CornerControl: number,
	StrokeThickness: number,
	ShadowOffset: number,
	WindowPadding: number,
	CardPadding: number,
	ControlHeight: number,
	TouchHeight: number,
	AnimationFast: number,
	AnimationNormal: number,
}

local Theme = {}

local DEFAULT: Theme = {
	Background = Color3.fromRGB(31, 34, 42),
	Panel = Color3.fromRGB(41, 46, 56),
	Surface = Color3.fromRGB(52, 59, 71),
	SurfaceRaised = Color3.fromRGB(61, 69, 82),
	SurfaceHover = Color3.fromRGB(70, 78, 92),
	Text = Color3.fromRGB(247, 241, 231),
	TextMuted = Color3.fromRGB(185, 178, 168),
	Accent = Color3.fromRGB(255, 156, 107),
	AccentPressed = Color3.fromRGB(232, 132, 88),
	Positive = Color3.fromRGB(125, 198, 157),
	Warning = Color3.fromRGB(239, 198, 110),
	Danger = Color3.fromRGB(229, 107, 107),
	Outline = Color3.fromRGB(21, 24, 30),
	Shadow = Color3.fromRGB(14, 16, 20),
	Overlay = Color3.fromRGB(11, 13, 17),
	FontDisplay = Enum.Font.FredokaOne,
	FontBody = Enum.Font.GothamMedium,
	FontBold = Enum.Font.GothamBold,
	TextTitle = 24,
	TextHeading = 16,
	TextBody = 14,
	TextSmall = 12,
	CornerWindow = 20,
	CornerCard = 14,
	CornerControl = 10,
	StrokeThickness = 2,
	ShadowOffset = 7,
	WindowPadding = 18,
	CardPadding = 14,
	ControlHeight = 58,
	TouchHeight = 48,
	AnimationFast = 0.1,
	AnimationNormal = 0.22,
}

local PRESETS: {[string]: {[string]: any}} = {
	Warm = {},
	Mint = {
		Accent = Color3.fromRGB(116, 205, 166),
		AccentPressed = Color3.fromRGB(91, 181, 143),
	},
	Blueberry = {
		Accent = Color3.fromRGB(124, 161, 255),
		AccentPressed = Color3.fromRGB(98, 132, 226),
	},
	Plum = {
		Accent = Color3.fromRGB(190, 139, 234),
		AccentPressed = Color3.fromRGB(162, 109, 207),
	},
	Pearl = {
		Background = Color3.fromRGB(232, 227, 217),
		Panel = Color3.fromRGB(247, 242, 232),
		Surface = Color3.fromRGB(255, 250, 241),
		SurfaceRaised = Color3.fromRGB(240, 234, 224),
		SurfaceHover = Color3.fromRGB(230, 222, 211),
		Text = Color3.fromRGB(38, 40, 46),
		TextMuted = Color3.fromRGB(103, 101, 97),
		Outline = Color3.fromRGB(54, 55, 61),
		Shadow = Color3.fromRGB(123, 116, 105),
		Overlay = Color3.fromRGB(30, 31, 35),
	},
}

local function cloneTable(source: {[string]: any}): {[string]: any}
	local result = {}
	for key, value in pairs(source) do
		result[key] = value
	end
	return result
end

function Theme.Create(overrides: {[string]: any}?): Theme
	local result = cloneTable(DEFAULT)
	if overrides then
		for key, value in pairs(overrides) do
			if result[key] == nil then
				warn(string.format("[Endware] Unknown theme token %q was ignored.", tostring(key)))
			else
				result[key] = value
			end
		end
	end
	return result :: Theme
end

function Theme.Resolve(value: string | {[string]: any} | nil): Theme
	if value == nil then
		return Theme.Create()
	end
	if type(value) == "string" then
		local preset = PRESETS[value]
		assert(preset ~= nil, string.format("[Endware] Unknown theme preset %q.", value))
		return Theme.Create(preset)
	end
	return Theme.Create(value)
end

function Theme.GetPresets(): {[string]: Theme}
	local result = {}
	for name, overrides in pairs(PRESETS) do
		result[name] = Theme.Create(overrides)
	end
	return result
end

Theme.Default = Theme.Create()
Theme.Presets = PRESETS

return Theme

end

__modules["Components/ControlBase"] = function(__require)

local Cleanup = __require("Core/Cleanup")

local ControlBase = {}
ControlBase.__index = ControlBase

export type Options = {
	Root: GuiObject,
	Window: any,
	Value: any,
	Render: ((any, boolean) -> ())?,
	Callback: ((...any) -> ())?,
	Normalize: ((any) -> any)?,
}

function ControlBase.new(options: Options): any
	local cleanup = Cleanup.new()
	cleanup:Give(options.Root)
	options.Window._cleanup:Give(cleanup)
	local self = setmetatable({
		_cleanup = cleanup,
		_root = options.Root,
		_window = options.Window,
		_value = options.Value,
		_render = options.Render,
		_callback = options.Callback,
		_normalize = options.Normalize,
		_disabled = false,
		_destroyed = false,
	}, ControlBase)
	if self._render then
		self._render(self._value, false)
	end
	return self
end

function ControlBase:Get(): any
	return self._value
end

function ControlBase:Set(value: any, setOptions: any?)
	if self._destroyed then
		return self
	end
	if self._normalize then
		value = self._normalize(value)
	end
	self._value = value
	if self._render then
		self._render(value, self._disabled)
	end
	if setOptions and setOptions.FireCallback == true and self._callback then
		self._window:_safeCall(self._callback, value)
	end
	return self
end

function ControlBase:_SetFromUser(value: any, ...: any)
	if self._destroyed or self._disabled then
		return
	end
	if self._normalize then
		value = self._normalize(value)
	end
	self._value = value
	if self._render then
		self._render(value, self._disabled)
	end
	if self._callback then
		self._window:_safeCall(self._callback, value, ...)
	end
end

function ControlBase:SetDisabled(disabled: boolean)
	self._disabled = disabled
	self._root.Active = not disabled
	if self._render then
		self._render(self._value, disabled)
	end
	return self
end

function ControlBase:SetVisible(visible: boolean)
	self._root.Visible = visible
	return self
end

function ControlBase:Destroy()
	if self._destroyed then
		return
	end
	self._destroyed = true
	self._cleanup:Destroy()
end

return ControlBase

end

__modules["Components/Checkbox"] = function(__require)

local Create = __require("Utility/Create")
local TweenUtil = __require("Utility/Tween")
local ControlBase = __require("Components/ControlBase")

local Checkbox = {}

function Checkbox.new(section: any, options: any): any
	local window = section._window
	local row = section:_createControl(options.Text or options.Name or "Checkbox", options.Description, 62, 62)
	local button = Create("TextButton", {
		Name = "CheckboxButton",
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, -14, 0.5, 0),
		Size = UDim2.fromOffset(34, 34),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "",
		ZIndex = row.ZIndex + 2,
		Parent = row,
	}) :: TextButton
	window:_corner(button, "CornerControl")
	local stroke = window:_stroke(button, "Outline", "StrokeThickness")
	local mark = Create("TextLabel", {
		Name = "Mark",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromOffset(25, 25),
		BackgroundTransparency = 1,
		Text = "✓",
		TextScaled = true,
		Font = Enum.Font.GothamBold,
		TextTransparency = 1,
		ZIndex = button.ZIndex + 1,
		Parent = button,
	}) :: TextLabel
	window:_bind(mark, "TextColor3", "Background")
	local scale = Create("UIScale", { Scale = 0.65, Parent = mark }) :: UIScale

	local controller: any
	local function render(value: boolean, disabled: boolean)
		button.BackgroundColor3 = if value then window._theme.Accent else window._theme.SurfaceRaised
		button.BackgroundTransparency = if disabled then 0.35 else 0
		stroke.Transparency = if disabled then 0.55 else 0
		mark.TextTransparency = if value then 0 else 1
		scale.Scale = if value then 1 else 0.65
	end
	controller = ControlBase.new({
		Root = row,
		Window = window,
		Value = options.Default == true,
		Render = render,
		Callback = options.Callback,
		Normalize = function(value)
			return value == true
		end,
	})

	window._cleanup:Give(button.Activated:Connect(function()
		if controller._disabled then
			return
		end
		local nextValue = not controller:Get()
		controller:_SetFromUser(nextValue)
		TweenUtil.Play(window._cleanup, scale, window._theme.AnimationFast, { Scale = 1.14 }, window:_reducedMotion())
		task.delay(window._theme.AnimationFast, function()
			if mark.Parent then
				TweenUtil.Play(window._cleanup, scale, window._theme.AnimationFast, { Scale = 1 }, window:_reducedMotion())
			end
		end)
	end))
	window:_buttonFeedback(button, "SurfaceRaised", "SurfaceHover", nil, function()
		return controller._disabled or controller:Get()
	end)
	return controller
end

return Checkbox

end

__modules["Components/Button"] = function(__require)

local Create = __require("Utility/Create")
local TweenUtil = __require("Utility/Tween")
local Cleanup = __require("Core/Cleanup")

local Button = {}

function Button.new(section: any, options: any): any
	local window = section._window
	local row = section:_createControl(options.Text or options.Name or "Button", options.Description, 64, 150)
	local action = Create("TextButton", {
		Name = "Action",
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, -14, 0.5, 0),
		Size = UDim2.fromOffset(126, 40),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = options.ActionText or options.ButtonText or "RUN",
		TextSize = window._theme.TextSmall,
		Font = window._theme.FontBold,
		ZIndex = row.ZIndex + 2,
		Parent = row,
	}) :: TextButton
	window:_corner(action, "CornerControl")
	window:_bind(action, "TextSize", "TextSmall")
	window:_bind(action, "Font", "FontBold")
	window:_bind(action, "BackgroundColor3", if options.Danger then "Danger" else "Accent")
	window:_bind(action, "TextColor3", "Background")
	local scale = Create("UIScale", { Scale = 1, Parent = action }) :: UIScale
	local disabled = false
	local destroyed = false
	local cleanup = Cleanup.new()
	cleanup:Give(row)
	window._cleanup:Give(cleanup)

	local controller = {}
	function controller:Get()
		return nil
	end
	function controller:SetDisabled(value: boolean)
		disabled = value
		action.Active = not value
		action.BackgroundTransparency = if value then 0.45 else 0
		return controller
	end
	function controller:SetVisible(value: boolean)
		row.Visible = value
		return controller
	end
	function controller:Fire()
		if destroyed or disabled then
			return
		end
		window:_safeCall(options.Callback)
	end
	function controller:Destroy()
		if destroyed then
			return
		end
		destroyed = true
		cleanup:Destroy()
	end

	cleanup:Give(action.Activated:Connect(function()
		if disabled then
			return
		end
		TweenUtil.Play(cleanup, scale, window._theme.AnimationFast, { Scale = 0.94 }, window:_reducedMotion())
		task.delay(window._theme.AnimationFast, function()
			if action.Parent then
				TweenUtil.Play(cleanup, scale, window._theme.AnimationFast, { Scale = 1 }, window:_reducedMotion())
			end
		end)
		controller:Fire()
	end))
	return controller
end

return Button

end

__modules["Components/Slider"] = function(__require)

local UserInputService = game:GetService("UserInputService")

local Create = __require("Utility/Create")
local MathUtil = __require("Utility/Math")
local Input = __require("Utility/Input")
local ControlBase = __require("Components/ControlBase")
local Validation = __require("Utility/Validation")

local Slider = {}

function Slider.new(section: any, options: any): any
	local window = section._window
	local minimum = options.Min or 0
	local maximum = options.Max or 100
	local step = options.Step or 1
	Validation.NumberRange(minimum, maximum)
	local row = section:_createStackedControl(options.Text or options.Name or "Slider", options.Description, 94)
	local valueLabel = window:_label(row, "", "TextSmall", "FontBold")
	valueLabel.AnchorPoint = Vector2.new(1, 0)
	valueLabel.Position = UDim2.new(1, -14, 0, 14)
	valueLabel.Size = UDim2.fromOffset(92, 22)
	valueLabel.TextXAlignment = Enum.TextXAlignment.Right
	window:_bind(valueLabel, "TextColor3", "Accent")

	local track = Create("TextButton", {
		Name = "Track",
		Position = UDim2.new(0, 14, 1, -31),
		Size = UDim2.new(1, -28, 0, 12),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "",
		ZIndex = row.ZIndex + 2,
		Parent = row,
	}) :: TextButton
	window:_corner(track, "CornerControl")
	window:_bind(track, "BackgroundColor3", "SurfaceRaised")
	local fill = Create("Frame", {
		Name = "Fill",
		Size = UDim2.fromScale(0, 1),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		ZIndex = track.ZIndex + 1,
		Parent = track,
	}) :: Frame
	window:_corner(fill, "CornerControl")
	window:_bind(fill, "BackgroundColor3", "Accent")
	local handle = Create("Frame", {
		Name = "Handle",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0, 0.5),
		Size = UDim2.fromOffset(24, 24),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		ZIndex = track.ZIndex + 3,
		Parent = track,
	}) :: Frame
	window:_corner(handle, "CornerControl")
	window:_bind(handle, "BackgroundColor3", "Text")
	window:_stroke(handle, "Outline", "StrokeThickness")

	local suffix = options.Suffix or ""
	local controller: any
	local function normalize(value: number): number
		local rounded = MathUtil.RoundToStep(math.clamp(tonumber(value) or minimum, minimum, maximum), step)
		return math.clamp(rounded, minimum, maximum)
	end
	local function render(value: number, disabled: boolean)
		local alpha = (value - minimum) / (maximum - minimum)
		fill.Size = UDim2.fromScale(alpha, 1)
		handle.Position = UDim2.fromScale(alpha, 0.5)
		valueLabel.Text = string.format("%s%s", tostring(value), suffix)
		track.BackgroundTransparency = if disabled then 0.35 else 0
		handle.BackgroundTransparency = if disabled then 0.35 else 0
	end
	controller = ControlBase.new({
		Root = row,
		Window = window,
		Value = normalize(options.Default or minimum),
		Render = render,
		Callback = options.Callback,
		Normalize = normalize,
	})

	local dragging = false
	local function updateFromX(x: number)
		if controller._disabled then
			return
		end
		local width = math.max(track.AbsoluteSize.X, 1)
		local alpha = math.clamp((x - track.AbsolutePosition.X) / width, 0, 1)
		controller:_SetFromUser(minimum + (maximum - minimum) * alpha)
	end
	controller._cleanup:Give(track.InputBegan:Connect(function(inputObject: InputObject)
		if Input.IsPrimary(inputObject) then
			dragging = true
			updateFromX(inputObject.Position.X)
		end
	end))
	controller._cleanup:Give(UserInputService.InputChanged:Connect(function(inputObject: InputObject)
		if dragging and Input.IsPointerMove(inputObject) then
			updateFromX(inputObject.Position.X)
		end
	end))
	controller._cleanup:Give(UserInputService.InputEnded:Connect(function(inputObject: InputObject)
		if Input.IsPrimary(inputObject) then
			dragging = false
		end
	end))
	return controller
end

return Slider

end

__modules["Components/Dropdown"] = function(__require)

local Create = __require("Utility/Create")
local ControlBase = __require("Components/ControlBase")
local Validation = __require("Utility/Validation")

local Dropdown = {}

function Dropdown.new(section: any, options: any): any
	local window = section._window
	local values = Validation.Array(options.Options or options.Values or {}, "Dropdown.Options")
	assert(#values > 0, "[Endware] Dropdown.Options must contain at least one value.")
	local row = section:_createStackedControl(options.Text or options.Name or "Dropdown", options.Description, 100)
	local selector = Create("TextButton", {
		Name = "Selector",
		Position = UDim2.new(0, 14, 1, -47),
		Size = UDim2.new(1, -28, 0, 36),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "",
		ZIndex = row.ZIndex + 2,
		Parent = row,
	}) :: TextButton
	window:_corner(selector, "CornerControl")
	window:_bind(selector, "BackgroundColor3", "SurfaceRaised")
	window:_stroke(selector, "Outline", "StrokeThickness")
	local selectedLabel = window:_label(selector, "", "TextSmall", "FontBold")
	selectedLabel.Position = UDim2.fromOffset(12, 0)
	selectedLabel.Size = UDim2.new(1, -44, 1, 0)
	window:_bind(selectedLabel, "TextColor3", "Text")
	local arrow = window:_label(selector, "▾", "TextBody", "FontBold")
	arrow.AnchorPoint = Vector2.new(1, 0)
	arrow.Position = UDim2.new(1, -10, 0, 0)
	arrow.Size = UDim2.fromOffset(24, 36)
	arrow.TextXAlignment = Enum.TextXAlignment.Center
	window:_bind(arrow, "TextColor3", "TextMuted")

	local function contains(value: any): boolean
		for _, item in ipairs(values) do
			if item == value then
				return true
			end
		end
		return false
	end
	local function normalize(value: any): any
		if contains(value) then
			return value
		end
		return values[1]
	end
	local controller: any
	local function render(value: any, disabled: boolean)
		selectedLabel.Text = tostring(value)
		selector.BackgroundTransparency = if disabled then 0.38 else 0
		arrow.TextTransparency = if disabled then 0.5 else 0
	end
	controller = ControlBase.new({
		Root = row,
		Window = window,
		Value = normalize(options.Default or values[1]),
		Render = render,
		Callback = options.Callback,
		Normalize = normalize,
	})

	function controller:SetOptions(nextValues: {any}, preserveSelection: boolean?)
		assert(#nextValues > 0, "[Endware] Dropdown options cannot be empty.")
		values = table.clone(nextValues)
		if not preserveSelection or not contains(controller:Get()) then
			controller:Set(values[1])
		end
		return controller
	end

	controller._cleanup:Give(selector.Activated:Connect(function()
		if controller._disabled then
			return
		end
		window:_showDropdown(selector, values, controller:Get(), function(value)
			controller:_SetFromUser(value)
		end)
	end))
	window:_buttonFeedback(selector, "SurfaceRaised", "SurfaceHover", "Surface", function()
		return controller._disabled
	end)
	return controller
end

return Dropdown

end

__modules["Components/TextInput"] = function(__require)

local Create = __require("Utility/Create")
local ControlBase = __require("Components/ControlBase")

local TextInput = {}

function TextInput.new(section: any, options: any): any
	local window = section._window
	local row = section:_createStackedControl(options.Text or options.Name or "Text input", options.Description, 104)
	local box = Create("TextBox", {
		Name = "Input",
		Position = UDim2.new(0, 14, 1, -49),
		Size = UDim2.new(1, -28, 0, 38),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		ClearTextOnFocus = options.ClearTextOnFocus == true,
		PlaceholderText = options.Placeholder or "Type here...",
		PlaceholderColor3 = window._theme.TextMuted,
		Text = tostring(options.Default or ""),
		TextXAlignment = Enum.TextXAlignment.Left,
		TextSize = window._theme.TextBody,
		Font = window._theme.FontBody,
		ZIndex = row.ZIndex + 2,
		Parent = row,
	}) :: TextBox
	window:_corner(box, "CornerControl")
	window:_bind(box, "TextSize", "TextBody")
	window:_bind(box, "Font", "FontBody")
	window:_bind(box, "BackgroundColor3", "SurfaceRaised")
	window:_bind(box, "TextColor3", "Text")
	window:_bind(box, "PlaceholderColor3", "TextMuted")
	window:_stroke(box, "Outline", "StrokeThickness")
	Create("UIPadding", {
		PaddingLeft = UDim.new(0, 12),
		PaddingRight = UDim.new(0, 12),
		Parent = box,
	})

	local controller: any
	local updating = false
	local function normalize(value: any): string
		local text = tostring(value or "")
		local maxLength = tonumber(options.MaxLength)
		if maxLength and #text > maxLength then
			text = string.sub(text, 1, maxLength)
		end
		return text
	end
	local function render(value: string, disabled: boolean)
		if box.Text ~= value then
			updating = true
			box.Text = value
			updating = false
		end
		box.TextEditable = not disabled
		box.BackgroundTransparency = if disabled then 0.38 else 0
	end
	controller = ControlBase.new({
		Root = row,
		Window = window,
		Value = normalize(options.Default or ""),
		Render = render,
		Callback = options.Callback,
		Normalize = normalize,
	})

	controller._cleanup:Give(box:GetPropertyChangedSignal("Text"):Connect(function()
		if updating or controller._disabled then
			return
		end
		local normalized = normalize(box.Text)
		if normalized ~= box.Text then
			updating = true
			box.Text = normalized
			updating = false
		end
		controller._value = normalized
		if options.Live == true and controller._callback then
			window:_safeCall(controller._callback, normalized)
		end
	end))
	controller._cleanup:Give(box.FocusLost:Connect(function(enterPressed: boolean)
		if controller._disabled then
			return
		end
		controller._value = normalize(box.Text)
		if options.Live ~= true and controller._callback then
			window:_safeCall(controller._callback, controller._value, enterPressed)
		end
	end))
	return controller
end

return TextInput

end

__modules["Components/Paragraph"] = function(__require)

local Create = __require("Utility/Create")

local Paragraph = {}

function Paragraph.new(section: any, options: any): any
	local window = section._window
	local root = Create("Frame", {
		Name = "Paragraph",
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		LayoutOrder = section:_nextOrder(),
		Parent = section._controls,
	}) :: Frame
	window:_corner(root, "CornerControl")
	window:_bind(root, "BackgroundColor3", "SurfaceRaised")
	window:_stroke(root, "Outline", "StrokeThickness")
	Create("UIPadding", {
		PaddingTop = UDim.new(0, 14),
		PaddingRight = UDim.new(0, 14),
		PaddingBottom = UDim.new(0, 14),
		PaddingLeft = UDim.new(0, 14),
		Parent = root,
	})
	Create("UIListLayout", {
		Padding = UDim.new(0, 6),
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = root,
	})
	local title = window:_label(root, options.Title or options.Text or "Information", "TextBody", "FontBold")
	title.Size = UDim2.new(1, 0, 0, 0)
	title.AutomaticSize = Enum.AutomaticSize.Y
	title.TextWrapped = true
	window:_bind(title, "TextColor3", "Accent")
	local content = window:_label(root, options.Content or options.Description or "", "TextSmall", "FontBody")
	content.Size = UDim2.new(1, 0, 0, 0)
	content.AutomaticSize = Enum.AutomaticSize.Y
	content.TextWrapped = true
	window:_bind(content, "TextColor3", "TextMuted")
	local controller = {}
	function controller:Set(nextContent: string)
		content.Text = tostring(nextContent)
		return controller
	end
	function controller:Get(): string
		return content.Text
	end
	function controller:SetVisible(value: boolean)
		root.Visible = value
		return controller
	end
	function controller:SetDisabled(_value: boolean)
		return controller
	end
	function controller:Destroy()
		root:Destroy()
	end
	return controller
end

return Paragraph

end

__modules["Components/Divider"] = function(__require)

local Create = __require("Utility/Create")

local Divider = {}

function Divider.new(section: any, options: any?): any
	options = options or {}
	local window = section._window
	local root = Create("Frame", {
		Name = "Divider",
		Size = UDim2.new(1, 0, 0, if options.Text then 26 else 14),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		LayoutOrder = section:_nextOrder(),
		Parent = section._controls,
	}) :: Frame
	local line = Create("Frame", {
		AnchorPoint = Vector2.new(0, 0.5),
		Position = UDim2.new(0, 0, 0.5, 0),
		Size = UDim2.new(1, 0, 0, 2),
		BorderSizePixel = 0,
		Parent = root,
	}) :: Frame
	window:_bind(line, "BackgroundColor3", "Outline")
	if options.Text then
		local label = window:_label(root, tostring(options.Text), "TextSmall", "FontBold")
		label.AnchorPoint = Vector2.new(0.5, 0.5)
		label.Position = UDim2.fromScale(0.5, 0.5)
		label.Size = UDim2.fromOffset(140, 24)
		label.TextXAlignment = Enum.TextXAlignment.Center
		window:_bind(label, "TextColor3", "TextMuted")
		window:_bind(label, "BackgroundColor3", "Panel")
		label.BackgroundTransparency = 0
	end
	local controller = {}
	function controller:SetVisible(value: boolean)
		root.Visible = value
		return controller
	end
	function controller:Destroy()
		root:Destroy()
	end
	return controller
end

return Divider

end

__modules["Components/Notification"] = function(__require)

local Create = __require("Utility/Create")
local TweenUtil = __require("Utility/Tween")

local Notification = {}

function Notification.new(window: any, options: any): any
	local duration = tonumber(options.Duration) or 4
	local toast = Create("CanvasGroup", {
		Name = "Notification",
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		GroupTransparency = 1,
		LayoutOrder = window._notificationOrder,
		Parent = window._notificationHost,
	}) :: CanvasGroup
	window._notificationOrder += 1
	window:_corner(toast, "CornerCard")
	window:_bind(toast, "BackgroundColor3", "Surface")
	window:_stroke(toast, "Outline", "StrokeThickness")
	Create("UIPadding", {
		PaddingTop = UDim.new(0, 14),
		PaddingRight = UDim.new(0, 14),
		PaddingBottom = UDim.new(0, 14),
		PaddingLeft = UDim.new(0, 14),
		Parent = toast,
	})
	Create("UIListLayout", {
		Padding = UDim.new(0, 5),
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = toast,
	})
	local title = window:_label(toast, options.Title or "Endware", "TextBody", "FontBold")
	title.Size = UDim2.new(1, 0, 0, 0)
	title.AutomaticSize = Enum.AutomaticSize.Y
	window:_bind(title, "TextColor3", options.Tone == "Danger" and "Danger" or options.Tone == "Positive" and "Positive" or "Accent")
	local content = window:_label(toast, options.Content or options.Message or "", "TextSmall", "FontBody")
	content.Size = UDim2.new(1, 0, 0, 0)
	content.AutomaticSize = Enum.AutomaticSize.Y
	content.TextWrapped = true
	window:_bind(content, "TextColor3", "TextMuted")
	local scale = Create("UIScale", { Scale = 0.94, Parent = toast }) :: UIScale
	TweenUtil.Play(window._cleanup, toast, window._theme.AnimationNormal, { GroupTransparency = 0 }, window:_reducedMotion())
	TweenUtil.Play(window._cleanup, scale, window._theme.AnimationNormal, { Scale = 1 }, window:_reducedMotion())
	task.delay(duration, function()
		if not toast.Parent then
			return
		end
		local tween = TweenUtil.Play(window._cleanup, toast, window._theme.AnimationNormal, { GroupTransparency = 1 }, window:_reducedMotion())
		TweenUtil.Play(window._cleanup, scale, window._theme.AnimationNormal, { Scale = 0.96 }, window:_reducedMotion())
		if tween then
			tween.Completed:Once(function()
				if toast.Parent then
					toast:Destroy()
				end
			end)
		else
			toast:Destroy()
		end
	end)
	return toast
end

return Notification

end

__modules["Core/Section"] = function(__require)

local Create = __require("Utility/Create")
local Checkbox = __require("Components/Checkbox")
local Button = __require("Components/Button")
local Slider = __require("Components/Slider")
local Dropdown = __require("Components/Dropdown")
local TextInput = __require("Components/TextInput")
local Paragraph = __require("Components/Paragraph")
local Divider = __require("Components/Divider")

local Section = {}
Section.__index = Section

function Section.new(tab: any, options: any): any
	local window = tab._window
	local root = Create("Frame", {
		Name = "Section",
		Size = UDim2.new(1, -4, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		LayoutOrder = tab:_nextOrder(),
		ZIndex = 20,
		Parent = tab._content,
	}) :: Frame
	window:_corner(root, "CornerCard")
	window:_bind(root, "BackgroundColor3", "Panel")
	window:_stroke(root, "Outline", "StrokeThickness")
	Create("UIPadding", {
		PaddingTop = UDim.new(0, 16),
		PaddingRight = UDim.new(0, 16),
		PaddingBottom = UDim.new(0, 16),
		PaddingLeft = UDim.new(0, 16),
		Parent = root,
	})
	Create("UIListLayout", {
		Padding = UDim.new(0, 12),
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = root,
	})

	local header = Create("Frame", {
		Name = "Header",
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		LayoutOrder = 1,
		Parent = root,
	}) :: Frame
	Create("UIListLayout", {
		Padding = UDim.new(0, 4),
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = header,
	})
	local title = window:_label(header, options.Title or options.Name or "Section", "TextHeading", "FontBold")
	title.Size = UDim2.new(1, 0, 0, 0)
	title.AutomaticSize = Enum.AutomaticSize.Y
	title.TextWrapped = true
	window:_bind(title, "TextColor3", "Text")
	if options.Description and options.Description ~= "" then
		local description = window:_label(header, options.Description, "TextSmall", "FontBody")
		description.Size = UDim2.new(1, 0, 0, 0)
		description.AutomaticSize = Enum.AutomaticSize.Y
		description.TextWrapped = true
		window:_bind(description, "TextColor3", "TextMuted")
	end

	local controls = Create("Frame", {
		Name = "Controls",
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		LayoutOrder = 2,
		Parent = root,
	}) :: Frame
	Create("UIListLayout", {
		Padding = UDim.new(0, 9),
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = controls,
	})

	return setmetatable({
		_window = window,
		_tab = tab,
		_root = root,
		_controls = controls,
		_order = 0,
		_destroyed = false,
	}, Section)
end

function Section:_nextOrder(): number
	self._order += 1
	return self._order
end

function Section:_textBlock(row: Frame, titleText: string, descriptionText: string?, rightSpace: number)
	local window = self._window
	local holder = Create("Frame", {
		Name = "TextBlock",
		Position = UDim2.fromOffset(14, 12),
		Size = UDim2.new(1, -(28 + rightSpace), 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		ZIndex = row.ZIndex + 1,
		Parent = row,
	}) :: Frame
	Create("UIListLayout", {
		Padding = UDim.new(0, 4),
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = holder,
	})
	local title = window:_label(holder, titleText, "TextBody", "FontBold")
	title.Size = UDim2.new(1, 0, 0, 0)
	title.AutomaticSize = Enum.AutomaticSize.Y
	title.TextWrapped = true
	window:_bind(title, "TextColor3", "Text")
	if descriptionText and descriptionText ~= "" then
		local description = window:_label(holder, descriptionText, "TextSmall", "FontBody")
		description.Size = UDim2.new(1, 0, 0, 0)
		description.AutomaticSize = Enum.AutomaticSize.Y
		description.TextWrapped = true
		window:_bind(description, "TextColor3", "TextMuted")
	end
	return holder
end

function Section:_createControl(titleText: string, descriptionText: string?, minimumHeight: number, rightSpace: number): Frame
	local window = self._window
	local row = Create("Frame", {
		Name = "Control",
		Size = UDim2.new(1, 0, 0, minimumHeight),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		LayoutOrder = self:_nextOrder(),
		ZIndex = 30,
		Parent = self._controls,
	}) :: Frame
	Create("UISizeConstraint", {
		MinSize = Vector2.new(0, minimumHeight),
		Parent = row,
	})
	window:_corner(row, "CornerControl")
	window:_bind(row, "BackgroundColor3", "Surface")
	window:_stroke(row, "Outline", "StrokeThickness")
	self:_textBlock(row, titleText, descriptionText, rightSpace)
	return row
end

function Section:_createStackedControl(titleText: string, descriptionText: string?, minimumHeight: number): Frame
	local row = self:_createControl(titleText, descriptionText, minimumHeight, 0)
	local textBlock = row:FindFirstChild("TextBlock") :: Frame?
	if textBlock then
		textBlock.Size = UDim2.new(1, -28, 0, 0)
	end
	return row
end

function Section:CreateCheckbox(options: any): any
	return Checkbox.new(self, options)
end

function Section:CreateButton(options: any): any
	return Button.new(self, options)
end

function Section:CreateSlider(options: any): any
	return Slider.new(self, options)
end

function Section:CreateDropdown(options: any): any
	return Dropdown.new(self, options)
end

function Section:CreateTextInput(options: any): any
	return TextInput.new(self, options)
end

function Section:CreateParagraph(options: any): any
	return Paragraph.new(self, options)
end

function Section:CreateDivider(options: any?): any
	return Divider.new(self, options)
end

Section.AddToggle = Section.CreateCheckbox
Section.AddCheckbox = Section.CreateCheckbox
Section.AddButton = Section.CreateButton
Section.AddSlider = Section.CreateSlider
Section.AddDropdown = Section.CreateDropdown
Section.AddTextInput = Section.CreateTextInput
Section.AddParagraph = Section.CreateParagraph
Section.AddDivider = Section.CreateDivider

function Section:SetVisible(visible: boolean)
	self._root.Visible = visible
	return self
end

function Section:Destroy()
	if self._destroyed then
		return
	end
	self._destroyed = true
	self._root:Destroy()
end

return Section

end

__modules["Core/Tab"] = function(__require)

local Create = __require("Utility/Create")
local Section = __require("Core/Section")

local Tab = {}
Tab.__index = Tab

function Tab.new(window: any, options: any): any
	local button = Create("TextButton", {
		Name = "TabButton",
		Size = UDim2.fromOffset(112, 42),
		AutomaticSize = Enum.AutomaticSize.X,
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "",
		LayoutOrder = window:_nextTabOrder(),
		ZIndex = 30,
		Parent = window._tabContent,
	}) :: TextButton
	window:_corner(button, "CornerControl")
	window:_stroke(button, "Outline", "StrokeThickness")
	Create("UIPadding", {
		PaddingLeft = UDim.new(0, 16),
		PaddingRight = UDim.new(0, 16),
		Parent = button,
	})
	local buttonLabel = window:_label(button, options.Name or "Tab", "TextSmall", "FontBold")
	buttonLabel.Size = UDim2.fromScale(1, 1)
	buttonLabel.TextXAlignment = Enum.TextXAlignment.Center
	window:_bind(buttonLabel, "TextColor3", "Text")

	local page = Create("ScrollingFrame", {
		Name = tostring(options.Name or "Tab") .. "Page",
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		CanvasSize = UDim2.fromOffset(0, 0),
		AutomaticCanvasSize = Enum.AutomaticSize.Y,
		ScrollingDirection = Enum.ScrollingDirection.Y,
		ScrollBarThickness = 5,
		ScrollBarImageTransparency = 0.2,
		Visible = false,
		ClipsDescendants = true,
		ZIndex = 10,
		Parent = window._pages,
	}) :: ScrollingFrame
	window:_bind(page, "ScrollBarImageColor3", "Accent")
	local content = Create("Frame", {
		Name = "Content",
		Size = UDim2.new(1, -8, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		Parent = page,
	}) :: Frame
	Create("UIPadding", {
		PaddingTop = UDim.new(0, 4),
		PaddingRight = UDim.new(0, 4),
		PaddingBottom = UDim.new(0, 18),
		PaddingLeft = UDim.new(0, 4),
		Parent = content,
	})
	Create("UIListLayout", {
		Padding = UDim.new(0, 12),
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = content,
	})

	local self = setmetatable({
		_window = window,
		_name = options.Name or "Tab",
		_description = options.Description or "",
		_button = button,
		_buttonLabel = buttonLabel,
		_page = page,
		_content = content,
		_order = 0,
		_destroyed = false,
	}, Tab)

	window._cleanup:Give(button.Activated:Connect(function()
		self:Select()
	end))
	window:_buttonFeedback(button, "Surface", "SurfaceHover", "SurfaceRaised", function()
		return window._activeTab == self
	end)
	return self
end

function Tab:_nextOrder(): number
	self._order += 1
	return self._order
end

function Tab:_setActive(active: boolean)
	self._page.Visible = active
	self._button.BackgroundColor3 = if active then self._window._theme.Accent else self._window._theme.Surface
	self._buttonLabel.TextColor3 = if active then self._window._theme.Background else self._window._theme.Text
end

function Tab:Select()
	self._window:_selectTab(self)
	return self
end

function Tab:CreateSection(options: any): any
	return Section.new(self, options)
end

Tab.AddSection = Tab.CreateSection

function Tab:SetVisible(visible: boolean)
	self._button.Visible = visible
	if not visible and self._window._activeTab == self then
		for _, candidate in ipairs(self._window._tabs) do
			if candidate ~= self and candidate._button.Visible then
				candidate:Select()
				break
			end
		end
	end
	return self
end

function Tab:Destroy()
	if self._destroyed then
		return
	end
	self._destroyed = true
	local wasActive = self._window._activeTab == self
	for index, candidate in ipairs(self._window._tabs) do
		if candidate == self then
			table.remove(self._window._tabs, index)
			break
		end
	end
	self._button:Destroy()
	self._page:Destroy()
	if wasActive then
		self._window._activeTab = nil
		local nextTab = self._window._tabs[1]
		if nextTab then
			nextTab:Select()
		end
	end
end

return Tab

end

__modules["Core/ResponsiveController"] = function(__require)

local Workspace = game:GetService("Workspace")
local UserInputService = game:GetService("UserInputService")

local ResponsiveController = {}
ResponsiveController.__index = ResponsiveController

function ResponsiveController.new(window: any): any
	local self = setmetatable({
		_window = window,
		_cameraConnection = nil,
		_mode = "Desktop",
	}, ResponsiveController)
	local camera = Workspace.CurrentCamera
	if camera then
		self._cameraConnection = window._cleanup:Give(camera:GetPropertyChangedSignal("ViewportSize"):Connect(function()
			self:Update()
		end))
	end
	window._cleanup:Give(Workspace:GetPropertyChangedSignal("CurrentCamera"):Connect(function()
		if self._cameraConnection then
			self._cameraConnection:Disconnect()
			self._cameraConnection = nil
		end
		local nextCamera = Workspace.CurrentCamera
		if nextCamera then
			self._cameraConnection = window._cleanup:Give(nextCamera:GetPropertyChangedSignal("ViewportSize"):Connect(function()
				self:Update()
			end))
		end
		self:Update()
	end))
	self:Update()
	return self
end

function ResponsiveController:GetMode(): string
	return self._mode
end

function ResponsiveController:Update()
	local window = self._window
	local camera = Workspace.CurrentCamera
	if not camera or not window._host.Parent then
		return
	end
	local viewport = camera.ViewportSize
	local touch = UserInputService.TouchEnabled
	local phone = viewport.X < 680 or (touch and math.min(viewport.X, viewport.Y) < 560)
	local tablet = not phone and (touch or viewport.X < 1050)
	self._mode = if phone then "Phone" elseif tablet then "Tablet" else "Desktop"
	window._deviceMode = self._mode

	local width: number
	local height: number
	if phone then
		width = math.floor(viewport.X * 0.94)
		height = math.floor(viewport.Y * 0.84)
	elseif tablet then
		width = math.floor(math.min(760, viewport.X * 0.9))
		height = math.floor(math.min(620, viewport.Y * 0.86))
	else
		width = math.floor(math.min(760, viewport.X * 0.78))
		height = math.floor(math.min(510, viewport.Y * 0.8))
	end
	width = math.clamp(width, math.min(320, viewport.X - 12), math.max(320, viewport.X - 12))
	height = math.clamp(height, math.min(390, viewport.Y - 12), math.max(390, viewport.Y - 12))
	window._host.Size = UDim2.fromOffset(width, height)

	local headerHeight = if phone then 64 else 74
	local tabsHeight = if phone then 54 else 60
	window._header.Size = UDim2.new(1, 0, 0, headerHeight)
	window._tabsBar.Position = UDim2.fromOffset(0, headerHeight)
	window._tabsBar.Size = UDim2.new(1, 0, 0, tabsHeight)
	window._contentViewport.Position = UDim2.fromOffset(0, headerHeight + tabsHeight)
	window._contentViewport.Size = UDim2.new(1, 0, 1, -(headerHeight + tabsHeight))
	window._subtitle.Visible = not phone
	window._keyHint.Visible = not phone
	window._title.Position = if phone then UDim2.fromOffset(60, 10) else UDim2.fromOffset(68, 12)
	window._title.Size = if phone then UDim2.new(1, -112, 0, 42) else UDim2.new(1, -230, 0, 28)
	window._logo.Position = if phone then UDim2.fromOffset(14, 13) else UDim2.fromOffset(18, 16)
	window._close.Position = UDim2.new(1, -16, 0.5, 0)
	window._notificationHost.Size = UDim2.fromOffset(math.min(340, viewport.X - 24), math.min(520, viewport.Y - 24))
	self:ClampWindow()
	self:ClampMobileButton()
end

function ResponsiveController:ClampWindow()
	local window = self._window
	local rootSize = window._safeRoot.AbsoluteSize
	local hostSize = window._host.AbsoluteSize
	if rootSize.X <= 0 or rootSize.Y <= 0 then
		return
	end
	local maxX = math.max(0, (rootSize.X - hostSize.X) * 0.5 - 4)
	local maxY = math.max(0, (rootSize.Y - hostSize.Y) * 0.5 - 4)
	local current = window._host.Position
	window._host.Position = UDim2.new(
		0.5,
		math.clamp(current.X.Offset, -maxX, maxX),
		0.5,
		math.clamp(current.Y.Offset, -maxY, maxY)
	)
end

function ResponsiveController:MoveWindowFrom(startOffset: Vector2, delta: Vector2)
	if self._mode == "Phone" or self._window._draggable == false then
		return
	end
	self._window._host.Position = UDim2.new(0.5, startOffset.X + delta.X, 0.5, startOffset.Y + delta.Y)
	self:ClampWindow()
end

function ResponsiveController:ClampMobileButton()
	local button = self._window._mobileToggle
	if not button or not button.Parent then
		return
	end
	local bounds = self._window._safeRoot.AbsoluteSize
	local size = button.AbsoluteSize
	if bounds.X <= 0 or bounds.Y <= 0 then
		return
	end
	local absolute = button.AbsolutePosition - self._window._safeRoot.AbsolutePosition
	local x = math.clamp(absolute.X, 8, math.max(8, bounds.X - size.X - 8))
	local y = math.clamp(absolute.Y, 8, math.max(8, bounds.Y - size.Y - 8))
	button.AnchorPoint = Vector2.zero
	button.Position = UDim2.fromOffset(x, y)
end

return ResponsiveController

end

__modules["Core/VisibilityController"] = function(__require)

local TweenUtil = __require("Utility/Tween")

local VisibilityController = {}
VisibilityController.__index = VisibilityController

function VisibilityController.new(window: any, visible: boolean): any
	local self = setmetatable({
		_window = window,
		_visible = visible,
		_transition = 0,
	}, VisibilityController)
	if not visible then
		window._safeRoot.Visible = false
		window._host.GroupTransparency = 1
		window._windowScale.Scale = 0.96
		window._backdrop.BackgroundTransparency = 1
	end
	self:_syncMobile()
	return self
end

function VisibilityController:_syncMobile()
	local window = self._window
	window._mobileToggle.Visible = window._mobileToggleEnabled
		and game:GetService("UserInputService").TouchEnabled
		and not self._visible
end

function VisibilityController:SetVisible(visible: boolean)
	if self._visible == visible or self._window._destroyed then
		return
	end
	self._visible = visible
	self._transition += 1
	local transition = self._transition
	local window = self._window
	local duration = window._theme.AnimationNormal
	if visible then
		window._safeRoot.Visible = true
		window._host.GroupTransparency = 1
		window._windowScale.Scale = 0.96
		window._backdrop.BackgroundTransparency = 1
		TweenUtil.Play(window._cleanup, window._host, duration, { GroupTransparency = 0 }, window:_reducedMotion())
		TweenUtil.Play(window._cleanup, window._windowScale, duration, { Scale = 1 }, window:_reducedMotion())
		TweenUtil.Play(window._cleanup, window._backdrop, duration, { BackgroundTransparency = 0.44 }, window:_reducedMotion())
	else
		TweenUtil.Play(window._cleanup, window._host, duration, { GroupTransparency = 1 }, window:_reducedMotion())
		TweenUtil.Play(window._cleanup, window._windowScale, duration, { Scale = 0.96 }, window:_reducedMotion())
		local tween = TweenUtil.Play(window._cleanup, window._backdrop, duration, { BackgroundTransparency = 1 }, window:_reducedMotion())
		if tween then
			tween.Completed:Once(function()
				if transition == self._transition and not self._visible and window._safeRoot.Parent then
					window._safeRoot.Visible = false
				end
			end)
		else
			window._safeRoot.Visible = false
		end
	end
	self:_syncMobile()
end

function VisibilityController:Toggle()
	self:SetVisible(not self._visible)
end

function VisibilityController:IsVisible(): boolean
	return self._visible
end

return VisibilityController

end

__modules["Core/Window"] = function(__require)

local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local GuiService = game:GetService("GuiService")
local Workspace = game:GetService("Workspace")

local Create = __require("Utility/Create")
local TweenUtil = __require("Utility/Tween")
local Input = __require("Utility/Input")
local Cleanup = __require("Core/Cleanup")
local Theme = __require("Theme")
local ResponsiveController = __require("Core/ResponsiveController")
local VisibilityController = __require("Core/VisibilityController")
local Notification = __require("Components/Notification")
local Tab = __require("Core/Tab")

local Window = {}
Window.__index = Window

local nextWindowId = 0

type Binding = {
	Instance: any,
	Property: string,
	Token: string,
	Transform: ((any) -> any)?,
}

local function nextName(baseName: string): string
	nextWindowId += 1
	return string.format("%s_%d", baseName, nextWindowId)
end

function Window:_safeCall(callback: ((...any) -> ())?, ...: any)
	if callback == nil then
		return
	end
	local packed = table.pack(...)
	local callable = callback :: any
	local ok, message = xpcall(function()
		callable(table.unpack(packed, 1, packed.n))
	end, debug.traceback)
	if not ok then
		warn("[Endware] Callback failed:\n" .. tostring(message))
	end
end

function Window:_reducedMotion(): boolean
	local ok, value = pcall(function()
		return GuiService.ReducedMotionEnabled
	end)
	return ok and value == true
end

function Window:_bind(instance: any, property: string, token: string, transform: ((any) -> any)?)
	local binding: Binding = {
		Instance = instance,
		Property = property,
		Token = token,
		Transform = transform,
	}
	table.insert(self._bindings, binding)
	instance.Destroying:Once(function()
		for index = #self._bindings, 1, -1 do
			if self._bindings[index] == binding then
				table.remove(self._bindings, index)
				break
			end
		end
	end)
	local value = self._theme[token]
	if transform then
		value = transform(value)
	end
	instance[property] = value
	return instance
end

function Window:_applyTheme()
	for index = #self._bindings, 1, -1 do
		local binding = self._bindings[index]
		local instance = binding.Instance
		if typeof(instance) ~= "Instance" or instance.Parent == nil then
			table.remove(self._bindings, index)
		else
			local value = self._theme[binding.Token]
			if binding.Transform then
				value = binding.Transform(value)
			end
			local ok = pcall(function()
				instance[binding.Property] = value
			end)
			if not ok then
				table.remove(self._bindings, index)
			end
		end
	end
	for _, tab in ipairs(self._tabs) do
		tab:_setActive(tab == self._activeTab)
	end
end

function Window:_corner(parent: Instance, token: string): UICorner
	local corner = Create("UICorner", { Parent = parent }) :: UICorner
	self:_bind(corner, "CornerRadius", token, function(value: number)
		return UDim.new(0, value)
	end)
	return corner
end

function Window:_stroke(parent: Instance, colorToken: string, thicknessToken: string): UIStroke
	local stroke = Create("UIStroke", {
		ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		Transparency = 0,
		Parent = parent,
	}) :: UIStroke
	self:_bind(stroke, "Color", colorToken)
	self:_bind(stroke, "Thickness", thicknessToken)
	return stroke
end

function Window:_label(parent: Instance, text: string, sizeToken: string, fontToken: string): TextLabel
	local label = Create("TextLabel", {
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		Text = text,
		TextWrapped = false,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextYAlignment = Enum.TextYAlignment.Center,
		ZIndex = 40,
		Parent = parent,
	}) :: TextLabel
	self:_bind(label, "TextSize", sizeToken)
	self:_bind(label, "Font", fontToken)
	Create("UITextSizeConstraint", {
		MinTextSize = 10,
		MaxTextSize = 30,
		Parent = label,
	})
	return label
end

function Window:_buttonFeedback(
	button: GuiButton,
	normalToken: string,
	hoverToken: string,
	pressedToken: string?,
	locked: (() -> boolean)?,
	cleanupOverride: any?
)
	local cleanup = cleanupOverride or self._cleanup
	local hovering = false
	local pressing = false
	local function refresh()
		if locked and locked() then
			return
		end
		local token = normalToken
		if pressing and pressedToken then
			token = pressedToken
		elseif hovering then
			token = hoverToken
		end
		button.BackgroundColor3 = self._theme[token]
	end
	cleanup:Give(button.MouseEnter:Connect(function()
		hovering = true
		refresh()
	end))
	cleanup:Give(button.MouseLeave:Connect(function()
		hovering = false
		pressing = false
		refresh()
	end))
	cleanup:Give(button.InputBegan:Connect(function(inputObject: InputObject)
		if Input.IsPrimary(inputObject) then
			pressing = true
			refresh()
		end
	end))
	cleanup:Give(button.InputEnded:Connect(function(inputObject: InputObject)
		if Input.IsPrimary(inputObject) then
			pressing = false
			refresh()
		end
	end))
end

function Window:_nextTabOrder(): number
	self._tabOrder += 1
	return self._tabOrder
end

function Window:_selectTab(tab: any)
	if self._activeTab == tab or self._destroyed then
		return
	end
	self:_closeDropdown()
	local previous = self._activeTab
	self._activeTab = tab
	if previous then
		previous:_setActive(false)
	end
	tab:_setActive(true)
	tab._page.CanvasPosition = Vector2.zero
end

function Window:CreateTab(options: any): any
	assert(not self._destroyed, "[Endware] Cannot create a tab on a destroyed window.")
	local tab = Tab.new(self, options)
	table.insert(self._tabs, tab)
	if self._activeTab == nil then
		tab:Select()
	end
	return tab
end

Window.AddTab = Window.CreateTab

function Window:SetVisible(visible: boolean)
	self._visibility:SetVisible(visible)
	return self
end

function Window:Toggle()
	self._visibility:Toggle()
	return self
end

function Window:IsVisible(): boolean
	return self._visibility:IsVisible()
end

function Window:SetTitle(title: string, subtitle: string?)
	self._title.Text = tostring(title)
	if subtitle ~= nil then
		self._subtitle.Text = tostring(subtitle)
	end
	return self
end

function Window:SetTheme(themeValue: string | {[string]: any})
	self._theme = Theme.Resolve(themeValue)
	self:_applyTheme()
	return self
end

function Window:GetTheme(): any
	return table.clone(self._theme)
end

function Window:Notify(options: any)
	if self._destroyed then
		return nil
	end
	return Notification.new(self, options)
end

function Window:_closeDropdown()
	if self._dropdownCleanup then
		self._dropdownCleanup:Destroy()
		self._dropdownCleanup = nil
	elseif self._dropdownMenu then
		self._dropdownMenu:Destroy()
	end
	self._dropdownMenu = nil
	self._overlayShield.Visible = false
end

function Window:_showDropdown(anchor: GuiObject, values: {any}, selected: any, callback: (any) -> ())
	self:_closeDropdown()
	self._overlayShield.Visible = true
	local dropdownCleanup = Cleanup.new()
	self._dropdownCleanup = dropdownCleanup
	local menuHeight = math.min(224, 16 + #values * 40)
	local menu = Create("CanvasGroup", {
		Name = "DropdownMenu",
		Size = UDim2.fromOffset(math.max(180, anchor.AbsoluteSize.X), menuHeight),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		GroupTransparency = 1,
		ZIndex = 920,
		Parent = self._overlayRoot,
	}) :: CanvasGroup
	self._dropdownMenu = menu
	dropdownCleanup:Give(menu)
	self:_corner(menu, "CornerCard")
	self:_bind(menu, "BackgroundColor3", "Panel")
	self:_stroke(menu, "Outline", "StrokeThickness")

	local scroll = Create("ScrollingFrame", {
		Position = UDim2.fromOffset(8, 8),
		Size = UDim2.new(1, -16, 1, -16),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		CanvasSize = UDim2.fromOffset(0, 0),
		AutomaticCanvasSize = Enum.AutomaticSize.Y,
		ScrollingDirection = Enum.ScrollingDirection.Y,
		ScrollBarThickness = 4,
		ZIndex = menu.ZIndex + 1,
		Parent = menu,
	}) :: ScrollingFrame
	self:_bind(scroll, "ScrollBarImageColor3", "Accent")
	Create("UIListLayout", {
		Padding = UDim.new(0, 6),
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = scroll,
	})

	local function reposition()
		if not anchor.Parent or not menu.Parent then
			return
		end
		local rootPosition = self._overlayRoot.AbsolutePosition
		local rootSize = self._overlayRoot.AbsoluteSize
		local anchorPosition = anchor.AbsolutePosition - rootPosition
		local x = math.clamp(anchorPosition.X, 8, math.max(8, rootSize.X - menu.AbsoluteSize.X - 8))
		local belowY = anchorPosition.Y + anchor.AbsoluteSize.Y + 6
		local y = belowY
		if belowY + menuHeight > rootSize.Y - 8 then
			y = anchorPosition.Y - menuHeight - 6
		end
		y = math.clamp(y, 8, math.max(8, rootSize.Y - menuHeight - 8))
		menu.Position = UDim2.fromOffset(x, y)
	end

	for index, value in ipairs(values) do
		local optionButton = Create("TextButton", {
			Name = "Option",
			Size = UDim2.new(1, -2, 0, 34),
			BackgroundTransparency = 0,
			BorderSizePixel = 0,
			AutoButtonColor = false,
			Text = tostring(value),
			TextSize = self._theme.TextSmall,
			Font = self._theme.FontBold,
			TextXAlignment = Enum.TextXAlignment.Left,
			LayoutOrder = index,
			ZIndex = scroll.ZIndex + 1,
			Parent = scroll,
		}) :: TextButton
		Create("UIPadding", {
			PaddingLeft = UDim.new(0, 12),
			PaddingRight = UDim.new(0, 12),
			Parent = optionButton,
		})
		self:_corner(optionButton, "CornerControl")
		self:_bind(optionButton, "TextSize", "TextSmall")
		self:_bind(optionButton, "Font", "FontBold")
		optionButton.BackgroundColor3 = if value == selected then self._theme.Accent else self._theme.Surface
		optionButton.TextColor3 = if value == selected then self._theme.Background else self._theme.Text
		dropdownCleanup:Give(optionButton.Activated:Connect(function()
			callback(value)
			self:_closeDropdown()
		end))
		self:_buttonFeedback(
			optionButton,
			value == selected and "Accent" or "Surface",
			"SurfaceHover",
			"SurfaceRaised",
			nil,
			dropdownCleanup
		)
	end

	dropdownCleanup:Give(anchor:GetPropertyChangedSignal("AbsolutePosition"):Connect(reposition))
	dropdownCleanup:Give(anchor:GetPropertyChangedSignal("AbsoluteSize"):Connect(reposition))
	reposition()
	TweenUtil.Play(dropdownCleanup, menu, self._theme.AnimationFast, { GroupTransparency = 0 }, self:_reducedMotion())
end

function Window:_setupWindowDrag()
	local dragging = false
	local dragStart = Vector3.zero
	local startOffset = Vector2.zero
	self._cleanup:Give(self._header.InputBegan:Connect(function(inputObject: InputObject)
		if not Input.IsPrimary(inputObject) or self._deviceMode == "Phone" or self._draggable == false then
			return
		end
		dragging = true
		dragStart = inputObject.Position
		startOffset = Vector2.new(self._host.Position.X.Offset, self._host.Position.Y.Offset)
	end))
	self._cleanup:Give(UserInputService.InputChanged:Connect(function(inputObject: InputObject)
		if dragging and Input.IsPointerMove(inputObject) then
			local delta3 = inputObject.Position - dragStart
			self._responsive:MoveWindowFrom(startOffset, Vector2.new(delta3.X, delta3.Y))
		end
	end))
	self._cleanup:Give(UserInputService.InputEnded:Connect(function(inputObject: InputObject)
		if Input.IsPrimary(inputObject) then
			dragging = false
		end
	end))
end

function Window:_setupMobileDrag()
	local button = self._mobileToggle
	local success, detectorOrError = pcall(function()
		local detector = Instance.new("UIDragDetector")
		local detectorAny = detector :: any
		detectorAny.DragStyle = Enum.UIDragDetectorDragStyle.TranslatePlane
		detectorAny.ResponseStyle = Enum.UIDragDetectorResponseStyle.Offset
		detectorAny.BoundingUI = self._persistentRoot
		detectorAny.BoundingBehavior = Enum.UIDragDetectorBoundingBehavior.EntireObject
		detector.Parent = button
		return detector
	end)
	if success then
		local detector = detectorOrError :: any
		local startPosition = button.Position
		self._cleanup:Give(detector.DragStart:Connect(function()
			startPosition = button.Position
			self._mobileDragged = false
		end))
		self._cleanup:Give(button:GetPropertyChangedSignal("Position"):Connect(function()
			if math.abs(button.Position.X.Offset - startPosition.X.Offset) > 4
				or math.abs(button.Position.Y.Offset - startPosition.Y.Offset) > 4
			then
				self._mobileDragged = true
			end
		end))
		self._cleanup:Give(detector.DragEnd:Connect(function()
			self._responsive:ClampMobileButton()
			task.defer(function()
				self._mobileDragged = false
			end)
		end))
		return
	end

	warn("[Endware] UIDragDetector was unavailable; using the fallback mobile drag controller: " .. tostring(detectorOrError))
	local dragging = false
	local startInput = Vector3.zero
	local startPosition = Vector2.zero
	self._cleanup:Give(button.InputBegan:Connect(function(inputObject: InputObject)
		if Input.IsPrimary(inputObject) then
			dragging = true
			self._mobileDragged = false
			startInput = inputObject.Position
			startPosition = Vector2.new(button.Position.X.Offset, button.Position.Y.Offset)
		end
	end))
	self._cleanup:Give(UserInputService.InputChanged:Connect(function(inputObject: InputObject)
		if dragging and Input.IsPointerMove(inputObject) then
			local delta = inputObject.Position - startInput
			if math.abs(delta.X) > 4 or math.abs(delta.Y) > 4 then
				self._mobileDragged = true
			end
			button.Position = UDim2.fromOffset(startPosition.X + delta.X, startPosition.Y + delta.Y)
			self._responsive:ClampMobileButton()
		end
	end))
	self._cleanup:Give(UserInputService.InputEnded:Connect(function(inputObject: InputObject)
		if Input.IsPrimary(inputObject) then
			dragging = false
			task.defer(function()
				self._mobileDragged = false
			end)
		end
	end))
end

function Window.new(options: any?): any
	options = options or {}
	local localPlayer = Players.LocalPlayer
	assert(localPlayer ~= nil, "[Endware] Endware must run in a client LocalScript.")
	local playerGui = localPlayer:WaitForChild("PlayerGui")
	local cleanup = Cleanup.new()
	local theme = Theme.Resolve(options.Theme)
	local screenGui = Create("ScreenGui", {
		Name = nextName(options.GuiName or "EndwareUI"),
		ResetOnSpawn = false,
		IgnoreGuiInset = false,
		ZIndexBehavior = Enum.ZIndexBehavior.Global,
		DisplayOrder = options.DisplayOrder or 80,
		Parent = playerGui,
	}) :: ScreenGui
	pcall(function()
		screenGui.ScreenInsets = Enum.ScreenInsets.TopbarSafeInsets
		screenGui.SafeAreaCompatibility = Enum.SafeAreaCompatibility.None
		screenGui.ClipToDeviceSafeArea = true
	end)

	local self = setmetatable({
		_cleanup = cleanup,
		_screenGui = screenGui,
		_bindings = {},
		_theme = theme,
		_tabs = {},
		_activeTab = nil,
		_tabOrder = 0,
		_notificationOrder = 1,
		_dropdownMenu = nil,
		_dropdownCleanup = nil,
		_destroyed = false,
		_deviceMode = "Desktop",
		_draggable = options.Draggable ~= false,
		_mobileToggleEnabled = options.MobileToggle ~= false,
		_mobileDragged = false,
	}, Window)
	cleanup:Give(screenGui)

	local persistentRoot = Create("Frame", {
		Name = "PersistentRoot",
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ClipsDescendants = false,
		ZIndex = 700,
		Parent = screenGui,
	}) :: Frame
	local safeRoot = Create("Frame", {
		Name = "SafeRoot",
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ClipsDescendants = false,
		ZIndex = 1,
		Parent = screenGui,
	}) :: Frame
	local backdrop = Create("TextButton", {
		Name = "Backdrop",
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 0.44,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "",
		ZIndex = 2,
		Parent = safeRoot,
	}) :: TextButton
	self:_bind(backdrop, "BackgroundColor3", "Overlay")

	local host = Create("CanvasGroup", {
		Name = "WindowHost",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromOffset(760, 510),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		GroupTransparency = 0,
		ClipsDescendants = false,
		ZIndex = 10,
		Parent = safeRoot,
	}) :: CanvasGroup
	local windowScale = Create("UIScale", { Scale = 1, Parent = host }) :: UIScale
	local shadow = Create("Frame", {
		Name = "Shadow",
		Position = UDim2.fromOffset(theme.ShadowOffset, theme.ShadowOffset),
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 0.18,
		BorderSizePixel = 0,
		ZIndex = 10,
		Parent = host,
	}) :: Frame
	self:_corner(shadow, "CornerWindow")
	self:_bind(shadow, "Position", "ShadowOffset", function(value: number)
		return UDim2.fromOffset(value, value)
	end)
	self:_bind(shadow, "BackgroundColor3", "Shadow")
	local main = Create("Frame", {
		Name = "Window",
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		ClipsDescendants = true,
		ZIndex = 20,
		Parent = host,
	}) :: Frame
	self:_corner(main, "CornerWindow")
	self:_bind(main, "BackgroundColor3", "Background")
	self:_stroke(main, "Outline", "StrokeThickness")

	local header = Create("Frame", {
		Name = "Header",
		Size = UDim2.new(1, 0, 0, 74),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		Active = true,
		ZIndex = 30,
		Parent = main,
	}) :: Frame
	self:_bind(header, "BackgroundColor3", "Panel")
	local logo = Create("Frame", {
		Name = "Logo",
		Position = UDim2.fromOffset(18, 16),
		Size = UDim2.fromOffset(42, 42),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		ZIndex = 34,
		Parent = header,
	}) :: Frame
	self:_corner(logo, "CornerControl")
	self:_bind(logo, "BackgroundColor3", "Accent")
	self:_stroke(logo, "Outline", "StrokeThickness")
	local logoText = self:_label(logo, "E", "TextHeading", "FontDisplay")
	logoText.Size = UDim2.fromScale(1, 1)
	logoText.TextXAlignment = Enum.TextXAlignment.Center
	self:_bind(logoText, "TextColor3", "Background")
	local title = self:_label(header, options.Title or "Endware", "TextTitle", "FontDisplay")
	title.Position = UDim2.fromOffset(68, 12)
	title.Size = UDim2.new(1, -230, 0, 30)
	self:_bind(title, "TextColor3", "Text")
	local subtitle = self:_label(header, options.Subtitle or "Playful interface library", "TextSmall", "FontBody")
	subtitle.Position = UDim2.fromOffset(69, 40)
	subtitle.Size = UDim2.new(1, -240, 0, 20)
	self:_bind(subtitle, "TextColor3", "TextMuted")
	local keyHint = Create("Frame", {
		Name = "KeyHint",
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, -62, 0.5, 0),
		Size = UDim2.fromOffset(112, 36),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		ZIndex = 34,
		Parent = header,
	}) :: Frame
	self:_corner(keyHint, "CornerControl")
	self:_bind(keyHint, "BackgroundColor3", "Surface")
	self:_stroke(keyHint, "Outline", "StrokeThickness")
	local keyText = self:_label(keyHint, (options.ToggleKey or Enum.KeyCode.RightShift).Name, "TextSmall", "FontBold")
	keyText.Size = UDim2.fromScale(1, 1)
	keyText.TextXAlignment = Enum.TextXAlignment.Center
	self:_bind(keyText, "TextColor3", "TextMuted")
	local close = Create("TextButton", {
		Name = "Close",
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, -16, 0.5, 0),
		Size = UDim2.fromOffset(36, 36),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "×",
		TextSize = 22,
		Font = theme.FontBold,
		ZIndex = 40,
		Parent = header,
	}) :: TextButton
	self:_corner(close, "CornerControl")
	self:_bind(close, "Font", "FontBold")
	self:_bind(close, "TextSize", "TextHeading")
	self:_bind(close, "BackgroundColor3", "Surface")
	self:_bind(close, "TextColor3", "Text")
	self:_buttonFeedback(close, "Surface", "SurfaceHover", "SurfaceRaised")

	local tabsBar = Create("Frame", {
		Name = "TabsBar",
		Position = UDim2.fromOffset(0, 74),
		Size = UDim2.new(1, 0, 0, 60),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		ClipsDescendants = true,
		ZIndex = 26,
		Parent = main,
	}) :: Frame
	self:_bind(tabsBar, "BackgroundColor3", "Panel")
	local tabScroll = Create("ScrollingFrame", {
		Name = "TabScroll",
		Position = UDim2.fromOffset(16, 7),
		Size = UDim2.new(1, -32, 1, -14),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		CanvasSize = UDim2.fromOffset(0, 0),
		AutomaticCanvasSize = Enum.AutomaticSize.X,
		ScrollingDirection = Enum.ScrollingDirection.X,
		ScrollBarThickness = 0,
		ClipsDescendants = true,
		ZIndex = 27,
		Parent = tabsBar,
	}) :: ScrollingFrame
	local tabContent = Create("Frame", {
		Name = "TabContent",
		Size = UDim2.new(0, 0, 1, 0),
		AutomaticSize = Enum.AutomaticSize.X,
		BackgroundTransparency = 1,
		Parent = tabScroll,
	}) :: Frame
	Create("UIListLayout", {
		FillDirection = Enum.FillDirection.Horizontal,
		Padding = UDim.new(0, 8),
		SortOrder = Enum.SortOrder.LayoutOrder,
		VerticalAlignment = Enum.VerticalAlignment.Center,
		Parent = tabContent,
	})

	local contentViewport = Create("Frame", {
		Name = "ContentViewport",
		Position = UDim2.fromOffset(0, 134),
		Size = UDim2.new(1, 0, 1, -134),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		ClipsDescendants = true,
		ZIndex = 22,
		Parent = main,
	}) :: Frame
	self:_bind(contentViewport, "BackgroundColor3", "Background")
	local pages = Create("Frame", {
		Name = "Pages",
		Position = UDim2.fromOffset(16, 12),
		Size = UDim2.new(1, -32, 1, -20),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ClipsDescendants = true,
		ZIndex = 23,
		Parent = contentViewport,
	}) :: Frame

	local overlayRoot = Create("Frame", {
		Name = "OverlayRoot",
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ClipsDescendants = false,
		ZIndex = 900,
		Parent = safeRoot,
	}) :: Frame
	local overlayShield = Create("TextButton", {
		Name = "OverlayShield",
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "",
		Visible = false,
		ZIndex = 910,
		Parent = overlayRoot,
	}) :: TextButton

	local notificationHost = Create("Frame", {
		Name = "Notifications",
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.new(1, -12, 0, 12),
		Size = UDim2.fromOffset(340, 520),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ZIndex = 1000,
		Parent = persistentRoot,
	}) :: Frame
	Create("UIListLayout", {
		Padding = UDim.new(0, 10),
		HorizontalAlignment = Enum.HorizontalAlignment.Right,
		SortOrder = Enum.SortOrder.LayoutOrder,
		Parent = notificationHost,
	})

	local mobileToggle = Create("TextButton", {
		Name = "MobileToggle",
		AnchorPoint = Vector2.zero,
		Position = UDim2.new(1, -70, 1, -70),
		Size = UDim2.fromOffset(56, 56),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = "E",
		TextSize = 20,
		Font = theme.FontDisplay,
		Visible = false,
		ZIndex = 1100,
		Parent = persistentRoot,
	}) :: TextButton
	self:_corner(mobileToggle, "CornerCard")
	self:_bind(mobileToggle, "Font", "FontDisplay")
	self:_bind(mobileToggle, "TextSize", "TextHeading")
	self:_bind(mobileToggle, "BackgroundColor3", "Accent")
	self:_bind(mobileToggle, "TextColor3", "Background")
	self:_stroke(mobileToggle, "Outline", "StrokeThickness")

	self._persistentRoot = persistentRoot
	self._safeRoot = safeRoot
	self._backdrop = backdrop
	self._host = host
	self._windowScale = windowScale
	self._main = main
	self._header = header
	self._logo = logo
	self._title = title
	self._subtitle = subtitle
	self._keyHint = keyHint
	self._close = close
	self._tabsBar = tabsBar
	self._tabContent = tabContent
	self._contentViewport = contentViewport
	self._pages = pages
	self._overlayRoot = overlayRoot
	self._overlayShield = overlayShield
	self._notificationHost = notificationHost
	self._mobileToggle = mobileToggle

	self._responsive = ResponsiveController.new(self)
	self._visibility = VisibilityController.new(self, options.StartVisible ~= false)
	self:_setupWindowDrag()
	self:_setupMobileDrag()

	cleanup:Give(close.Activated:Connect(function()
		self:SetVisible(false)
	end))
	cleanup:Give(overlayShield.Activated:Connect(function()
		self:_closeDropdown()
	end))
	cleanup:Give(mobileToggle.Activated:Connect(function()
		if not self._mobileDragged then
			self:Toggle()
		end
	end))
	local toggleKey = options.ToggleKey
	if toggleKey == nil then
		toggleKey = Enum.KeyCode.RightShift
	end
	if toggleKey ~= Enum.KeyCode.Unknown then
		cleanup:Give(UserInputService.InputBegan:Connect(function(inputObject: InputObject, gameProcessed: boolean)
			if gameProcessed or Input.HasFocusedTextBox() then
				return
			end
			if inputObject.KeyCode == toggleKey then
				self:Toggle()
			end
		end))
	end
	cleanup:Give(backdrop.Activated:Connect(function()
		-- Deliberately does not dismiss the window to prevent accidental closes.
	end))
	cleanup:Give(GuiService:GetPropertyChangedSignal("ReducedMotionEnabled"):Connect(function()
		-- The next interaction automatically uses the new preference.
	end))
	self:_applyTheme()
	return self
end

function Window:Destroy()
	if self._destroyed then
		return
	end
	self._destroyed = true
	self:_closeDropdown()
	self._cleanup:Destroy()
end

return Window

end

__modules["init"] = function(__require)

local Theme = __require("Theme")
local Window = __require("Core/Window")

local Endware = {}
Endware.Version = "0.1.1"
Endware.Themes = Theme.GetPresets()

function Endware.CreateTheme(overrides: {[string]: any}?): any
	return Theme.Create(overrides)
end

function Endware.new(options: any?): any
	return Window.new(options)
end

function Endware.CreateWindow(selfOrOptions: any, possibleOptions: any?): any
	local options = if possibleOptions ~= nil then possibleOptions else selfOrOptions
	if options == Endware then
		options = nil
	end
	return Endware.new(options)
end

return Endware

end

local function __require(name: string): any
	if __cache[name] ~= nil then
		return __cache[name]
	end
	assert(not __loading[name], string.format("[Endware] Circular bundled module dependency: %s", name))
	local loader = __modules[name]
	assert(loader ~= nil, string.format("[Endware] Bundled module %q was not found.", name))
	__loading[name] = true
	local result = loader(__require)
	__loading[name] = nil
	assert(result ~= nil, string.format("[Endware] Bundled module %q returned nil.", name))
	__cache[name] = result
	return result
end

return __require("init")
